import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import NextAuthSessionProvider from "./provider";
import { Toaster } from "@/components/ui/sonner";
import Footer from "./_components/Footer";

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <NextAuthSessionProvider>
          <div className="flex flex-col justify-end">
            <div className="mx-2 md:mx-6 min-h-[100vh]">
              <Toaster />
              <Header />
              {children}
            </div>
            <Footer />
          </div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
